version: '2'
services:
  mysql:
    image: mysql:5.6
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=nicesecret
    ports:
      - "3306:3306"
    volumes:
      - pubmedb:/var/lib/mysql

  website:
    build: .
    ports:
      - "3000:3000"
    links:
      - mysql
    environment:
      - RAILS_ENV=production
      - DB_ENV=production
      - DB_HOST=mysql
      - DB_PASSWORD=nicesecret
      - DB_DATABASE=pub_me_development
    command: "/bin/bash -c 'rake docker:pause_for_db         && \
                            rake docker:create_database_yaml && \
                            rake docker:create_apis_yaml     && \
                            rails s'"
    restart: always

  website-migrate:
    build: .
    links:
      - mysql
    environment:
      - RAILS_ENV=production
      - DB_ENV=production
      - DB_HOST=mysql
      - DB_PASSWORD=nicesecret
      - DB_DATABASE=pub_me_development
    command: "/bin/bash -c 'rake docker:pause_for_db         && \
                            rake docker:create_database_yaml && \
                            rake db:create                   && \
                            rake db:migrate'"
    restart: "no"

networks:
  default:
    external:
      name: pubmenet

volumes:
  pubmedb:
    external: true
  pubmeenv:
    external: true
